use monitoreo;
DELIMITER $$
CREATE TRIGGER `after_data_insert` 
    AFTER INSERT ON `DATO` FOR EACH ROW
    BEGIN
        UPDATE DATO_ACTUAL SET DATO=NEW.DATO,FECHA=CURDATE(),HORA=CURTIME()  WHERE ID_SENSOR = NEW.ID_SENSOR; 
        INSERT REGISTRO VALUES(NULL, CURDATE(), CURTIME(), NEW.ID_DATO);
    END $$
DELIMITER ;

