package Modelo;
// Generated 19-03-2012 12:56:24 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DatoActual generated by hbm2java
 */
public class DatoActual  implements java.io.Serializable {


     private Integer idDatoActual;
     private String dato;
     private Date fecha;
     private Date hora;
     private int idSensor;

    public DatoActual() {
    }

	
    public DatoActual(int idSensor) {
        this.idSensor = idSensor;
    }
    public DatoActual(String dato, Date fecha, Date hora, int idSensor) {
       this.dato = dato;
       this.fecha = fecha;
       this.hora = hora;
       this.idSensor = idSensor;
    }
   
    public Integer getIdDatoActual() {
        return this.idDatoActual;
    }
    
    public void setIdDatoActual(Integer idDatoActual) {
        this.idDatoActual = idDatoActual;
    }
    public String getDato() {
        return this.dato;
    }
    
    public void setDato(String dato) {
        this.dato = dato;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public int getIdSensor() {
        return this.idSensor;
    }
    
    public void setIdSensor(int idSensor) {
        this.idSensor = idSensor;
    }




}


