package Modelo;
// Generated 19-03-2012 12:56:24 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Dato generated by hbm2java
 */
public class Dato  implements java.io.Serializable {


     private Integer idDato;
     private Sensor sensor;
     private Micro micro;
     private String dato;
     private Set<Registro> registros = new HashSet<Registro>(0);

    public Dato() {
    }

	
    public Dato(Micro micro) {
        this.micro = micro;
    }
    public Dato(Sensor sensor, Micro micro, String dato, Set<Registro> registros) {
       this.sensor = sensor;
       this.micro = micro;
       this.dato = dato;
       this.registros = registros;
    }
   
    public Integer getIdDato() {
        return this.idDato;
    }
    
    public void setIdDato(Integer idDato) {
        this.idDato = idDato;
    }
    public Sensor getSensor() {
        return this.sensor;
    }
    
    public void setSensor(Sensor sensor) {
        this.sensor = sensor;
    }
    public Micro getMicro() {
        return this.micro;
    }
    
    public void setMicro(Micro micro) {
        this.micro = micro;
    }
    public String getDato() {
        return this.dato;
    }
    
    public void setDato(String dato) {
        this.dato = dato;
    }
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }




}


