package Modelo;
// Generated 02-04-2012 02:50:57 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estacion generated by hbm2java
 */
public class Estacion  implements java.io.Serializable {


     private Integer idEstacion;
     private Comuna comuna;
     private String ip;
     private String nombreestacion;
     private Set<Micro> micros = new HashSet<Micro>(0);

    public Estacion() {
    }

    public Estacion(Comuna comuna, String ip, String nombreestacion, Set<Micro> micros) {
       this.comuna = comuna;
       this.ip = ip;
       this.nombreestacion = nombreestacion;
       this.micros = micros;
    }
   
    public Integer getIdEstacion() {
        return this.idEstacion;
    }
    
    public void setIdEstacion(Integer idEstacion) {
        this.idEstacion = idEstacion;
    }
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getNombreestacion() {
        return this.nombreestacion;
    }
    
    public void setNombreestacion(String nombreestacion) {
        this.nombreestacion = nombreestacion;
    }
    public Set<Micro> getMicros() {
        return this.micros;
    }
    
    public void setMicros(Set<Micro> micros) {
        this.micros = micros;
    }




}


