package Modelo;
// Generated 02-04-2012 02:50:57 PM by Hibernate Tools 3.2.1.GA



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idLogin;
     private TipoLogin tipoLogin;
     private String login;
     private String password;

    public Login() {
    }

	
    public Login(TipoLogin tipoLogin) {
        this.tipoLogin = tipoLogin;
    }
    public Login(TipoLogin tipoLogin, String login, String password) {
       this.tipoLogin = tipoLogin;
       this.login = login;
       this.password = password;
    }
   
    public Integer getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(Integer idLogin) {
        this.idLogin = idLogin;
    }
    public TipoLogin getTipoLogin() {
        return this.tipoLogin;
    }
    
    public void setTipoLogin(TipoLogin tipoLogin) {
        this.tipoLogin = tipoLogin;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


