package Modelo;
// Generated 02-04-2012 02:50:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RegistroAlarma generated by hbm2java
 */
public class RegistroAlarma  implements java.io.Serializable {


     private int idRegistroAlarma;
     private Alarma alarma;
     private Date fecha;
     private Date hora;

    public RegistroAlarma() {
    }

    public RegistroAlarma(int idRegistroAlarma, Alarma alarma, Date fecha, Date hora) {
       this.idRegistroAlarma = idRegistroAlarma;
       this.alarma = alarma;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public int getIdRegistroAlarma() {
        return this.idRegistroAlarma;
    }
    
    public void setIdRegistroAlarma(int idRegistroAlarma) {
        this.idRegistroAlarma = idRegistroAlarma;
    }
    public Alarma getAlarma() {
        return this.alarma;
    }
    
    public void setAlarma(Alarma alarma) {
        this.alarma = alarma;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


