package Modelo;
// Generated 19-03-2012 12:56:24 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private int regionId;
     private String regionNombre;
     private Set<Provincia> provincias = new HashSet<Provincia>(0);

    public Region() {
    }

	
    public Region(int regionId) {
        this.regionId = regionId;
    }
    public Region(int regionId, String regionNombre, Set<Provincia> provincias) {
       this.regionId = regionId;
       this.regionNombre = regionNombre;
       this.provincias = provincias;
    }
   
    public int getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(int regionId) {
        this.regionId = regionId;
    }
    public String getRegionNombre() {
        return this.regionNombre;
    }
    
    public void setRegionNombre(String regionNombre) {
        this.regionNombre = regionNombre;
    }
    public Set<Provincia> getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set<Provincia> provincias) {
        this.provincias = provincias;
    }




}


