package Modelo;
// Generated 19-03-2012 12:56:24 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private Integer idRegistro;
     private Dato dato;
     private Date fecha;
     private Date hora;

    public Registro() {
    }

	
    public Registro(Dato dato) {
        this.dato = dato;
    }
    public Registro(Dato dato, Date fecha, Date hora) {
       this.dato = dato;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Integer getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(Integer idRegistro) {
        this.idRegistro = idRegistro;
    }
    public Dato getDato() {
        return this.dato;
    }
    
    public void setDato(Dato dato) {
        this.dato = dato;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


