package Modelo;
// Generated 02-04-2012 02:50:57 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sensor generated by hbm2java
 */
public class Sensor  implements java.io.Serializable {


     private int idSensor;
     private String nombresensor;
     private String unidadmedida;
     private Integer maxima;
     private Integer minima;
     private Integer idMicro;
     private Set<Alarma> alarmas = new HashSet<Alarma>(0);
     private Set<Dato> datos = new HashSet<Dato>(0);

    public Sensor() {
    }

	
    public Sensor(int idSensor) {
        this.idSensor = idSensor;
    }
    public Sensor(int idSensor, String nombresensor, String unidadmedida, Integer maxima, Integer minima, Integer idMicro, Set<Alarma> alarmas, Set<Dato> datos) {
       this.idSensor = idSensor;
       this.nombresensor = nombresensor;
       this.unidadmedida = unidadmedida;
       this.maxima = maxima;
       this.minima = minima;
       this.idMicro = idMicro;
       this.alarmas = alarmas;
       this.datos = datos;
    }
   
    public int getIdSensor() {
        return this.idSensor;
    }
    
    public void setIdSensor(int idSensor) {
        this.idSensor = idSensor;
    }
    public String getNombresensor() {
        return this.nombresensor;
    }
    
    public void setNombresensor(String nombresensor) {
        this.nombresensor = nombresensor;
    }
    public String getUnidadmedida() {
        return this.unidadmedida;
    }
    
    public void setUnidadmedida(String unidadmedida) {
        this.unidadmedida = unidadmedida;
    }
    public Integer getMaxima() {
        return this.maxima;
    }
    
    public void setMaxima(Integer maxima) {
        this.maxima = maxima;
    }
    public Integer getMinima() {
        return this.minima;
    }
    
    public void setMinima(Integer minima) {
        this.minima = minima;
    }
    public Integer getIdMicro() {
        return this.idMicro;
    }
    
    public void setIdMicro(Integer idMicro) {
        this.idMicro = idMicro;
    }
    public Set<Alarma> getAlarmas() {
        return this.alarmas;
    }
    
    public void setAlarmas(Set<Alarma> alarmas) {
        this.alarmas = alarmas;
    }
    public Set<Dato> getDatos() {
        return this.datos;
    }
    
    public void setDatos(Set<Dato> datos) {
        this.datos = datos;
    }




}


