package Modelo;
// Generated 19-03-2012 12:56:24 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoAlarma generated by hbm2java
 */
public class TipoAlarma  implements java.io.Serializable {


     private int idTipo;
     private String tipoAlarma;
     private Set<Alarma> alarmas = new HashSet<Alarma>(0);

    public TipoAlarma() {
    }

	
    public TipoAlarma(int idTipo, String tipoAlarma) {
        this.idTipo = idTipo;
        this.tipoAlarma = tipoAlarma;
    }
    public TipoAlarma(int idTipo, String tipoAlarma, Set<Alarma> alarmas) {
       this.idTipo = idTipo;
       this.tipoAlarma = tipoAlarma;
       this.alarmas = alarmas;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getTipoAlarma() {
        return this.tipoAlarma;
    }
    
    public void setTipoAlarma(String tipoAlarma) {
        this.tipoAlarma = tipoAlarma;
    }
    public Set<Alarma> getAlarmas() {
        return this.alarmas;
    }
    
    public void setAlarmas(Set<Alarma> alarmas) {
        this.alarmas = alarmas;
    }




}


