package Modelo;
// Generated 02-04-2012 02:50:57 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoLogin generated by hbm2java
 */
public class TipoLogin  implements java.io.Serializable {


     private int idTipoLogin;
     private String nombreTipo;
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<Login> logins_1 = new HashSet<Login>(0);

    public TipoLogin() {
    }

	
    public TipoLogin(int idTipoLogin) {
        this.idTipoLogin = idTipoLogin;
    }
    public TipoLogin(int idTipoLogin, String nombreTipo, Set<Login> logins, Set<Login> logins_1) {
       this.idTipoLogin = idTipoLogin;
       this.nombreTipo = nombreTipo;
       this.logins = logins;
       this.logins_1 = logins_1;
    }
   
    public int getIdTipoLogin() {
        return this.idTipoLogin;
    }
    
    public void setIdTipoLogin(int idTipoLogin) {
        this.idTipoLogin = idTipoLogin;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }
    public Set<Login> getLogins_1() {
        return this.logins_1;
    }
    
    public void setLogins_1(Set<Login> logins_1) {
        this.logins_1 = logins_1;
    }




}


