package Modelo;
// Generated 02-04-2012 02:50:57 PM by Hibernate Tools 3.2.1.GA



/**
 * Variable generated by hbm2java
 */
public class Variable  implements java.io.Serializable {


     private Integer idVariable;
     private Integer valor;
     private String nombreVariable;

    public Variable() {
    }

    public Variable(Integer valor, String nombreVariable) {
       this.valor = valor;
       this.nombreVariable = nombreVariable;
    }
   
    public Integer getIdVariable() {
        return this.idVariable;
    }
    
    public void setIdVariable(Integer idVariable) {
        this.idVariable = idVariable;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }
    public String getNombreVariable() {
        return this.nombreVariable;
    }
    
    public void setNombreVariable(String nombreVariable) {
        this.nombreVariable = nombreVariable;
    }




}


