package Modelo.Zenoss;
// Generated 02-04-2012 02:56:43 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AlertState generated by hbm2java
 */
public class AlertState  implements java.io.Serializable {


     private AlertStateId id;
     private Date lastSent;

    public AlertState() {
    }

    public AlertState(AlertStateId id, Date lastSent) {
       this.id = id;
       this.lastSent = lastSent;
    }
   
    public AlertStateId getId() {
        return this.id;
    }
    
    public void setId(AlertStateId id) {
        this.id = id;
    }
    public Date getLastSent() {
        return this.lastSent;
    }
    
    public void setLastSent(Date lastSent) {
        this.lastSent = lastSent;
    }




}


