package Modelo.Zenoss;
// Generated 02-04-2012 02:56:43 PM by Hibernate Tools 3.2.1.GA



/**
 * DetailId generated by hbm2java
 */
public class DetailId  implements java.io.Serializable {


     private String evid;
     private String name;

    public DetailId() {
    }

    public DetailId(String evid, String name) {
       this.evid = evid;
       this.name = name;
    }
   
    public String getEvid() {
        return this.evid;
    }
    
    public void setEvid(String evid) {
        this.evid = evid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailId) ) return false;
		 DetailId castOther = ( DetailId ) other; 
         
		 return ( (this.getEvid()==castOther.getEvid()) || ( this.getEvid()!=null && castOther.getEvid()!=null && this.getEvid().equals(castOther.getEvid()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEvid() == null ? 0 : this.getEvid().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         return result;
   }   


}


