package Modelo.Zenoss;
// Generated 02-04-2012 02:56:43 PM by Hibernate Tools 3.2.1.GA



/**
 * Detail generated by hbm2java
 */
public class Detail  implements java.io.Serializable {


     private DetailId id;
     private Integer sequence;
     private String value;

    public Detail() {
    }

	
    public Detail(DetailId id) {
        this.id = id;
    }
    public Detail(DetailId id, Integer sequence, String value) {
       this.id = id;
       this.sequence = sequence;
       this.value = value;
    }
   
    public DetailId getId() {
        return this.id;
    }
    
    public void setId(DetailId id) {
        this.id = id;
    }
    public Integer getSequence() {
        return this.sequence;
    }
    
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


