package Modelo.Zenoss;
// Generated 02-04-2012 02:56:43 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Heartbeat generated by hbm2java
 */
public class Heartbeat  implements java.io.Serializable {


     private HeartbeatId id;
     private Integer timeout;
     private Date lastTime;

    public Heartbeat() {
    }

	
    public Heartbeat(HeartbeatId id, Date lastTime) {
        this.id = id;
        this.lastTime = lastTime;
    }
    public Heartbeat(HeartbeatId id, Integer timeout, Date lastTime) {
       this.id = id;
       this.timeout = timeout;
       this.lastTime = lastTime;
    }
   
    public HeartbeatId getId() {
        return this.id;
    }
    
    public void setId(HeartbeatId id) {
        this.id = id;
    }
    public Integer getTimeout() {
        return this.timeout;
    }
    
    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }
    public Date getLastTime() {
        return this.lastTime;
    }
    
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }




}


