package Modelo.Zenoss;
// Generated 02-04-2012 02:56:43 PM by Hibernate Tools 3.2.1.GA



/**
 * HeartbeatId generated by hbm2java
 */
public class HeartbeatId  implements java.io.Serializable {


     private String device;
     private String component;

    public HeartbeatId() {
    }

    public HeartbeatId(String device, String component) {
       this.device = device;
       this.component = component;
    }
   
    public String getDevice() {
        return this.device;
    }
    
    public void setDevice(String device) {
        this.device = device;
    }
    public String getComponent() {
        return this.component;
    }
    
    public void setComponent(String component) {
        this.component = component;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HeartbeatId) ) return false;
		 HeartbeatId castOther = ( HeartbeatId ) other; 
         
		 return ( (this.getDevice()==castOther.getDevice()) || ( this.getDevice()!=null && castOther.getDevice()!=null && this.getDevice().equals(castOther.getDevice()) ) )
 && ( (this.getComponent()==castOther.getComponent()) || ( this.getComponent()!=null && castOther.getComponent()!=null && this.getComponent().equals(castOther.getComponent()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDevice() == null ? 0 : this.getDevice().hashCode() );
         result = 37 * result + ( getComponent() == null ? 0 : this.getComponent().hashCode() );
         return result;
   }   


}


